### ISSUE TITLE
Dynamic fitting

### ISSUE THREAD

**Issue by licode** [scikit-xray/scikit-xray#164]
We need to think about smart data structure to handle dynamic fitting. It means that the input parameters for next fitting run depend on the previous fitting results, also fitting strategy varies gradually with different parameters either turn on or turn off.

**Comment by danielballan** [comment]
`Fitter` might be the right solution for the first part of this. But we might want our own subclass of `Model` to be safe (i.e., in control).

**Comment by licode** [comment]
I think this is done.
