### ISSUE TITLE
Make pyfai an optional dependency

### ISSUE THREAD

**Issue by ericdill** [scikit-xray/scikit-xray#309]
Pyfai is a PITA to build with conda and we are only using it for one function right now. Therefore I would advocate we remove it from the conda recipe

**Comment by ericdill** [comment]
Oh joy of joys... pyfai is also not python 3 compatible!

**Comment by licode** [comment]
Agree, I also got some issues installing this.

**Comment by tacaswell** [comment]
closed by #312

**Comment by tacaswell** [comment]
@ericdill Looks like the master branch is https://github.com/kif/pyFAI/blob/master/.travis.yml as they are testing against 3.4
